version: '3.8'

services:
  web:
    image: irinanazarova/images:v4.04.2021
    restart: always
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    expose:
      - 8000
  nginx:
    image: nginx:1.19.0
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - ./media:/code/media