# Generated by Django 3.1.4 on 2021-04-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_remove_image_image_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_file",
            new_name="image",
        ),
    ]
